upstream fastcgi_backend_php81 {
  server php81:9000;
}

upstream fastcgi_backend_php82 {
  server php82:9000;
}

map $http_host $MAGE_RUN_CODE_MIT {
   au.mit.test '';
   hh.mit.test homehardware;
}

server {
   server_name *.mit.test;

   set $MAGE_ROOT /var/www/projects82/mit;
   set $MAGE_RUN_TYPE website;
   set $MAGE_RUN_CODE $MAGE_RUN_CODE_MIT;

   include /var/www/projects82/nginx.conf;
}

map $http_host $MAGE_RUN_CODE_KRI {
   au.kri.test '';
   nz.kri.test krispy_kreme_nz;
}

server {
    server_name *.kri.test;

    set $MAGE_ROOT /var/www/projects81/kri;
    set $MAGE_RUN_TYPE store;
    set $MAGE_RUN_CODE $MAGE_RUN_CODE_KRI;

    include /var/www/projects81/nginx.conf;
}
