map $http_host $MAGE_RUN_CODE_UOM {
   uom.test '';
   merchandise.test merchandise;
   advancement.test advancement;
}

server {
    listen 80;
    listen 443 ssl;

    ssl_certificate      /etc/ssl/fullchain.pem;
    ssl_certificate_key  /etc/ssl/privkey.pem;

    server_name uom.test merchandise.test advancement.test;

    set $MAGE_ROOT /var/www/projects81/uom;
    set $MAGE_RUN_TYPE website;
    set $MAGE_RUN_CODE $MAGE_RUN_CODE_UOM;

    include /var/www/projects81/nginx.conf;
}
